CREATE TABLE USERS(ID INT not null AUTO_INCREMENT,NAME VARCHAR(50), LOGIN VARCHAR(100),PASSWORD VARCHAR(100) ,PRIMARY KEY(ID));
CREATE TABLE ROLES(ID INT not null AUTO_INCREMENT, NAME VARCHAR(50),DESCRIPTION VARCHAR(100), PRIMARY KEY (ID));
CREATE TABLE USER_ROLES(USER_ID INT not null, ROLE_ID INT not null, FOREIGN KEY (USER_ID) REFERENCES USERS(ID), FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID));
CREATE TABLE ARTICLE (ID INT not null AUTO_INCREMENT, CONTEXT VARCHAR(100),CONTENT VARCHAR(2000), CREATOR_ID INT, TOPIC_ID INT, DATE VARCHAR(20),PRIMARY KEY (ID), FOREIGN KEY (CREATOR_ID) REFERENCES USERS(ID));
CREATE TABLE TOPIC (ID INT not null AUTO_INCREMENT, NAME VARCHAR(25), DESCRIPTION VARCHAR(100), PRIMARY KEY (ID));